services:
  - type: web
    name: waveai-v3
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python waveai_v2_simple.py
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PYTHONUNBUFFERED
        value: 1
    healthCheckPath: /